apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  # Server configuration
  server.insecure: "true"
  
  # OIDC configuration
  server.enable.proxy.extension: "true"
  server.oidc.config: "true"
  
  # Additional security settings
  server.rbac.log.enforce.enable: "true"
  
  # Disable local users if desired (uncomment to disable)
  # server.disable.auth: "false"