apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-itlusions-com
spec:
  secretName: argocd-itlusions-com-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: argocd.itlusions.com
  dnsNames:
    - argocd.itlusions.nl
    - argocd.itlusions.com