apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingressroute
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`argocd.dev.itlusions.com`)
      kind: Rule
      services:
        - name: argocd-server
          namespace: argocd
          port: 80
    - match: Host(`argocd.dev.itlusions.nl`)
      kind: Rule
      services:
        - name: argocd-server
          namespace: argocd
          port: 80
  tls:
    secretName: argocd-dev.itlusions-com-tls