apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-argocd-test
  labels:
    app: {{ .Release.Name }}-argocd-test
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-argocd-test